import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const font = localFont({
  src: "../public/NotoSansSC-Regular.ttf",
  weight: "normal",
  display: "swap",
  preload: true,
  variable: "--font-NotoSansSC-Regular",
});

export const metadata: Metadata = {
  title: "语音服务工具",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
